### ISSUE TITLE
Understanding the Example given by the Professor in the pdf

### ISSUE THREAD

**Issue by joseplatas** [joseplatas/csc401_hw3#1]
For example: above map shows that to go from city 0 to city 5, the shortest path to follow is 0-1- 2-5, with shortest distance between city 0 and 5 is 6274.

I dont understand where is he getting 6274 from @krather. 
I thought that the weight was suppose to be calculated like this
0-1-2-5
1000+2800+2500 = 6300

**Comment by krather** [comment]
We're given the X and Y coordinates of the cities, not the direct distance between them.

We need to use Pythagorean 's theorem to get the actual distance between the two cities. 
http://www.mathwarehouse.com/algebra/distance_formula/index.php
Add up all these weights and you get 6274 (if you round).

The calculateWeights method implements that distance formula.

**Comment by joseplatas** [comment]
Thank you @krather . I realize that when i saw your function you created.
